### ISSUE TITLE
COMPRESSION 

### ISSUE THREAD

**Issue by luisas** [nf-core/multiplesequencealign#9]

**Comment by alessiovignoli** [comment]
The compression step is actually happening on the alignment outputs files. So it happens before the evaluate. It is a skipable step. And if it is run the files are actually saved as compressed. It should create a copy during compression because the un-compress version is actually passed to the evaluation step as that can not read compressed files.

**Comment by alessiovignoli** [comment]
The file is compressed by pigzip (pgzip) module.
